name: Deploy
run-name: deno is running Deploy Actions 

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: checkout
      
        uses: actions/checkout@v4

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: deploy
        run: pnpm i && pnpm --prefix src/frontend i && npm run build

      - name: Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: blive
          entrypoint: src/backend/server.ts
